kumuluzee:
  name: lairbnb-notifications
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8084
    http:
      port: 8084
  discovery:
    etcd:
      hosts: http://192.168.99.100:2379
    ttl: 20
    ping-interval: 15
  logs:
    config-file: '<?xml version="1.0" encoding="UTF-8"?>
                  <Configuration name="notifications">
                      <Appenders>
                          <Console name="console" target="SYSTEM_OUT">
                              <PatternLayout pattern="%d %p %marker %m %X %ex %n"/>
                          </Console>
                          <Socket name="logstash" host="9133958c-d366-47ba-8103-32d02e80e198-ls.logit.io" port="14664"
                                                                                                        protocol="tcp">
                              <JSONLayout complete="false" compact="true" eventEol="true" charset="UTF-8"
                                                                                                    properties="true"/>
                          </Socket>
                      </Appenders>
                      <Loggers>
                          <!-- Default logger -->
                          <Root level="all">
                              <AppenderRef ref="console" level="info"/>
                              <AppenderRef ref="logstash" level="trace"/>
                          </Root>
                      </Loggers>
                  </Configuration>'