apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: notifications-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: notifications
    spec:
      containers:
      - image: rlamp/lairbnb-notifications:latest
        name: notifications
        env:
          - name: KUMULUZEE_DISCOVERY_CLUSTER
            value: bluemix
          - name: KUMULUZEE_DISCOVERY_ETCD_HOSTS
            value: http://etcd:2379
        ports:
        - containerPort: 8083
          name: server
          protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: notifications
spec:
  type: NodePort
  ports:
  - port: 8083
    protocol: TCP
    targetPort: 8083
  selector:
    app: notifications
